# Site settings
# These are used to personalize your new site.
title: Thomas Ramsey # your name here
logo: "/images/github.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Computer-Science (class of 2022)
  <br /><br />
  <a href="https://github.com/tjramsey/tjramsey.github.io/blob/master/pdf/Resume%20(2).pdf">View My Resume</a>
  <br />
repository: "csci-csu/csci-portfolio"
github_username:  tjramsey # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

